/**
 * Production `ImageGenerationProvider` — the first REAL (non-Unconfigured,
 * non-test) image-*generation* provider implementation in this codebase.
 * (`ProductionImageProcessingProvider`, remove.bg, was the first real
 * vendor call of any kind — Phase 4. This is the generation-domain
 * counterpart the CLAUDE.md/docs/generation.md "No real image-generation
 * vendor is installed" note has referred to ever since.)
 *
 * ## Why this contract, not one specific named vendor's SDK
 *
 * No AI generation vendor is selected or documented anywhere in this
 * repository (checked `docs/ai-pipeline.md`, `docs/generation.md`,
 * `lib/validation/env.server.ts` before writing this file — none name
 * one). Arbitrarily hardcoding one commercial vendor's exact, undocumented
 * -in-this-repo request/response shape here — without the ability to test
 * it against a live account in this environment — risks shipping code
 * that LOOKS like a real integration but has never actually been verified
 * against that vendor's real API, which is worse than being explicit
 * about the boundary.
 *
 * Instead, this implements a genuinely real, working HTTP client against
 * a fully-specified, documented JSON contract (see docs/ai-providers.md)
 * that closely follows the widely-adopted "OpenAI Images API-compatible"
 * shape (`prompt`/`n`/`size`/`response_format` in, `data[].b64_json` or
 * `data[].url` out) — the closest thing to a de facto standard in this
 * space, already implemented by multiple hosted and self-hosted vendors
 * specifically so client code written against it is portable. A merchant
 * who configures `AI_PROVIDER_BASE_URL`/`AI_PROVIDER_API_KEY` against any
 * endpoint speaking this contract gets a genuinely working integration
 * today, with zero code changes. A vendor with a materially different
 * wire shape needs its own adapter file alongside this one, behind the
 * same `ImageGenerationProvider` interface — that adapter is exactly what
 * remains vendor-specific and not yet built (see docs/ai-providers.md
 * "What remains vendor-specific").
 *
 * Selected by services/generation/provider.server.ts whenever `AI_PROVIDER`
 * is set to anything other than the test seam's own `"deterministic-test"`
 * value AND `AI_PROVIDER_BASE_URL`/`AI_PROVIDER_API_KEY` are both present —
 * mirrors services/processing/provider.server.ts's exact resolver shape.
 * `AI_PROVIDER_API_KEY` is read only via lib/validation/env.server.ts,
 * never hardcoded, never logged (see SECRET_ENV_KEYS) — and the signed
 * storage URLs this provider's caller (job.server.ts) later generates are
 * never passed to or logged by this file at all; this file only ever
 * emits raw generated bytes upward.
 */
import { getEnv } from "../../lib/validation/env.server";
import { logger } from "../../lib/logging/logger.server";
import { fetchWithTimeout, measureLatencyMs, ProviderRequestError, ProviderResponseError } from "./http-provider-utils.server";
import type { GenerateImageInput, GenerateImageResult, GeneratedImageOutput, ImageGenerationProvider } from "./types";

/** Generous enough for a multi-output generative request under normal
 * vendor load (these calls are inherently slower than remove.bg's
 * single-image transform); short enough that a hung request fails within
 * one HTTP cycle rather than blocking a worker slot indefinitely.
 * Overridable via `AI_PROVIDER_TIMEOUT_MS` for a vendor that's
 * predictably slower/faster than this default. */
const DEFAULT_REQUEST_TIMEOUT_MS = 60_000;

/** Maps a curated aspect ratio string (services/generation/types.ts's
 * `ASPECT_RATIOS` — this file never imports that union directly, per
 * CLAUDE.md's domain-boundary rule that `services/ai/` stays generic) to
 * a "{width}x{height}" size hint, capped at `maxDimension` on the longer
 * side and rounded to the nearest multiple of 8 (a common diffusion-model
 * convention that avoids edge artifacts on many vendors). An
 * unrecognized ratio falls back to a square — never throws, since a
 * malformed `aspectRatio` reaching this far is a validation gap upstream
 * (services/generation/schema.ts), not this provider's problem to police
 * strictly. */
export function sizeForAspectRatio(aspectRatio: string, maxDimension = 1024): string {
  const match = /^(\d+):(\d+)$/.exec(aspectRatio);
  if (!match) return `${maxDimension}x${maxDimension}`;

  const ratioW = Number(match[1]);
  const ratioH = Number(match[2]);
  if (!Number.isFinite(ratioW) || !Number.isFinite(ratioH) || ratioW <= 0 || ratioH <= 0) {
    return `${maxDimension}x${maxDimension}`;
  }

  const roundTo8 = (n: number) => Math.max(8, Math.round(n / 8) * 8);
  const width = ratioW >= ratioH ? maxDimension : Math.round((maxDimension * ratioW) / ratioH);
  const height = ratioH >= ratioW ? maxDimension : Math.round((maxDimension * ratioH) / ratioW);
  return `${roundTo8(width)}x${roundTo8(height)}`;
}

/** Maps this app's curated quality tier to the contract's `quality`
 * field — vendors implementing this contract commonly accept
 * "standard"/"hd" (again, the OpenAI-Images-API-compatible convention);
 * "draft" maps to "standard" since there's no cheaper tier in this
 * contract to request. */
function qualityForTier(quality: string): string {
  return quality === "high" ? "hd" : "standard";
}

interface ContractResponseItem {
  b64_json?: string;
  url?: string;
  revised_prompt?: string;
}

interface ContractResponse {
  created?: number;
  model?: string;
  id?: string;
  data?: ContractResponseItem[];
}

function isContractResponse(value: unknown): value is ContractResponse {
  return typeof value === "object" && value !== null;
}

export class ProductionImageGenerationProvider implements ImageGenerationProvider {
  readonly name = "production";

  async generateImage(input: GenerateImageInput): Promise<GenerateImageResult> {
    const env = getEnv();
    if (!env.AI_PROVIDER_BASE_URL || !env.AI_PROVIDER_API_KEY) {
      // Resolver-level double-check — see provider.server.ts, which
      // should never construct this class without both set. Kept here
      // too so this class is safe to unit-test/instantiate directly.
      throw new Error("ProductionImageGenerationProvider requires AI_PROVIDER_BASE_URL and AI_PROVIDER_API_KEY.");
    }

    const timeoutMs = env.AI_PROVIDER_TIMEOUT_MS ?? DEFAULT_REQUEST_TIMEOUT_MS;
    const negativeConstraints = input.creativeDirection.negativeConstraints ?? [];

    const requestBody = {
      model: env.AI_PROVIDER_MODEL || "default",
      prompt: input.creativeDirection.prompt,
      ...(negativeConstraints.length > 0 ? { negative_prompt: negativeConstraints.join(", ") } : {}),
      n: input.outputCount,
      size: sizeForAspectRatio(input.aspectRatio),
      quality: qualityForTier(input.quality),
      response_format: "b64_json",
    };

    logger.info("ai_provider.generation.request", {
      provider: this.name,
      generationType: input.generationType,
      outputCount: input.outputCount,
      aspectRatio: input.aspectRatio,
      attempt: input.attempt,
      // Never the prompt text itself or the base URL/key — see module
      // doc comment. A generic "a request was made" event is enough for
      // observability; the prompt is merchant-facing product creative
      // detail, not something that belongs in ops logs.
    });

    let response: Response;
    let latencyMs: number;
    try {
      const measured = await measureLatencyMs(() =>
        fetchWithTimeout(`${env.AI_PROVIDER_BASE_URL}/v1/images/generations`, "calling the image generation provider", timeoutMs, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${env.AI_PROVIDER_API_KEY}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify(requestBody),
        }),
      );
      response = measured.result;
      latencyMs = measured.latencyMs;
    } catch (error) {
      logger.error("ai_provider.generation.request_failed", {
        provider: this.name,
        reason: error instanceof Error ? error.name : "unknown",
      });
      throw error;
    }

    if (!response.ok) {
      // Never log or forward the raw response body — it may echo back
      // request content or vendor-internal detail. Status code alone is
      // enough for classification/observability (see CLAUDE.md "Safe
      // error handling").
      logger.error("ai_provider.generation.request_failed", { provider: this.name, status: response.status });
      throw new ProviderRequestError(this.name, response.status);
    }

    let parsed: unknown;
    try {
      parsed = await response.json();
    } catch {
      throw new ProviderResponseError(this.name, "response body was not valid JSON");
    }
    if (!isContractResponse(parsed) || !Array.isArray(parsed.data) || parsed.data.length === 0) {
      throw new ProviderResponseError(this.name, "response had no data[] entries");
    }

    const contentType = `image/${input.outputFormat}`;
    const outputs: GeneratedImageOutput[] = await Promise.all(
      parsed.data.map(async (item, index): Promise<GeneratedImageOutput> => {
        const data = await this.resolveOutputBytes(item, timeoutMs);
        return {
          data,
          contentType,
          providerResultId: parsed.id ? `${parsed.id}-${index}` : undefined,
          metadata: {
            latencyMs,
            model: parsed.model ?? env.AI_PROVIDER_MODEL ?? null,
            revisedPrompt: item.revised_prompt ?? null,
          },
        };
      }),
    );

    logger.info("ai_provider.generation.completed", {
      provider: this.name,
      outputCount: outputs.length,
      latencyMs,
    });

    return {
      outputs,
      providerJobId: parsed.id,
      raw: { model: parsed.model, created: parsed.created },
    };
  }

  /** One output item can carry either inline base64 bytes or a URL to
   * fetch — see module doc comment for why this contract supports both. */
  private async resolveOutputBytes(item: ContractResponseItem, timeoutMs: number): Promise<Uint8Array> {
    if (item.b64_json) {
      return new Uint8Array(Buffer.from(item.b64_json, "base64"));
    }
    if (item.url) {
      const response = await fetchWithTimeout(item.url, "fetching a generated image output", timeoutMs);
      if (!response.ok) {
        throw new ProviderRequestError(this.name, response.status, "fetching a generated image output");
      }
      return new Uint8Array(await response.arrayBuffer());
    }
    throw new ProviderResponseError(this.name, "a data[] entry had neither b64_json nor url");
  }
}
